### ISSUE TITLE
Best way to "stop" the action

### ISSUE THREAD

**Issue by rafaelss** [fnando/rack-api#6]
Hey,

```
class MyAPI < Rack::API
  get "/" do
    return if params[:foo].blank?

    # ...
  end
end
```

How can I do that without get `LocalJumpError: unexpected return` errors?

**Comment by fnando** [comment]
Try using next instead. next "returns" from blocks on Ruby.

Abraços,

## 

Nando Vieira

**Comment by rafaelss** [comment]
I'm doing that, I was just wondering if rack-api would have something like sinatra's `halt` ;)

https://github.com/sinatra/sinatra/blob/186a5bc9b66ac163e4f74a88c3406a1587d97eae/lib/sinatra/base.rb#L416
